# Copyright the Hyperledger Blockchain Explorer contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Build docker image

on:
  workflow_dispatch: # workflow_dispatch must be enabled in main branch to support release action on older release branches
  create:
    tags:
      - v*
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "postgres-Dockerfile"

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  # on tag vx.y.z created, create docker tag x.y.z
  build-and-push-docker-release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            component: explorer
          - dockerfile: ./postgres-Dockerfile
            component: explorer-db
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          config-inline: |
            [worker.oci]
              max-parallelism = 1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.component }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Login to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.component }} Image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
